package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.RelativeId
import jetbrains.buildServer.configs.kotlin.ui.add
import jetbrains.buildServer.configs.kotlin.ui.changeBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            param("Test Param1", "env.AGENT_NAME")
        }
        add {
            param("Test Param 3", "asdasdas4")
        }
        add {
            password("secure.myPassword", "zxx6cd39160615a50fb")
        }
        add {
            param("Test Param 2", "Test Param 2")
        }
    }
}
